apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: clusternet
spec:
  homepage: https://github.com/clusternet/kubectl-clusternet
  shortDescription: "Wrap multiple kubectl calls to Clusternet"
  description: |
    A plugin to interact with Clusternet.
  version: {{ .TagName }}
  caveats: |
    For additional options:
      $ kubectl clusternet --help
      or https://github.com/clusternet/kubectl-clusternet/blob/main/doc/USAGE.md
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/clusternet/kubectl-clusternet/releases/download/{{ .TagName }}/kubectl-clusternet_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "./kubectl-clusternet"
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-clusternet
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/clusternet/kubectl-clusternet/releases/download/{{ .TagName }}/kubectl-clusternet_darwin_arm64.tar.gz" .TagName }}
    files:
    - from: "./kubectl-clusternet"
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-clusternet
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/clusternet/kubectl-clusternet/releases/download/{{ .TagName }}/kubectl-clusternet_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "./kubectl-clusternet"
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-clusternet
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/clusternet/kubectl-clusternet/releases/download/{{ .TagName }}/kubectl-clusternet_linux_arm64.tar.gz" .TagName }}
    files:
    - from: "./kubectl-clusternet"
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-clusternet
  - selector:
      matchLabels:
        os: linux
        arch: arm
    {{addURIAndSha "https://github.com/clusternet/kubectl-clusternet/releases/download/{{ .TagName }}/kubectl-clusternet_linux_armv6.tar.gz" .TagName }}
    files:
    - from: "./kubectl-clusternet"
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-clusternet
  - selector:
      matchLabels:
        os: linux
        arch: 386
    {{addURIAndSha "https://github.com/clusternet/kubectl-clusternet/releases/download/{{ .TagName }}/kubectl-clusternet_linux_i386.tar.gz" .TagName }}
    files:
    - from: "./kubectl-clusternet"
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-clusternet
